### ISSUE TITLE
System.ArgumentNullException: Argument cannot be null.

### ISSUE THREAD

**Issue by DVLNarayana** [rebuy-de/rb-forms-barcode#30]
05-21 11:37:17.624 I/Choreographer( 4568): Skipped 47 frames!  The application may be doing too much work on its main thread.
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568): [BarcodeDecoder] System.ArgumentNullException: Argument cannot be null.
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568): Parameter name: src
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568):   at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal:copy_from_unmanaged (intptr,int,System.Array,int)
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568):   at System.Runtime.InteropServices.Marshal.Copy (IntPtr source, System.Byte[] destination, Int32 startIndex, Int32 length) [0x00000] in <filename unknown>:0 
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568):   at ApxLabs.FastAndroidCamera.FastJavaByteArray.CopyTo (System.Byte[] array, Int32 arrayIndex) [0x00000] in <filename unknown>:0 
05-21 11:37:17.794 D/Rb.Forms.Barcode( 4568):   at Rb.Forms.Barcode.Droid.Decoder.BarcodeDecoder.decode (ApxLabs.FastAndroidCamera.FastJavaByteArray buffer, Int32 width, Int32 height) [0x00000] in <filename unknown>:0 
05-21 11:37:17.874 I/art     ( 4568): Explicit concurrent mark sweep GC freed 8560(538KB) AllocSpace objects, 0(0B) LOS objects, 12% free, 110MB/126MB, paused 405us total 12.135ms
05-21 11:37:17.879 D/Mono    ( 4568): GC_OLD_BRIDGE num-objects 95 num_hash_entries 4868 sccs size 3345 init 0.00ms df1 9.62ms sort 1.11ms dfs2 2.85ms setup-cb 0.24ms free-data 1.80ms links 7784/7784/6489/2 dfs passes 12747/11129
05-21 11:37:17.879 D/Mono    ( 4568): GC_MINOR: (Nursery full) pause 19.31ms, total 19.44ms, bridge 22.62ms promoted 496K major 1792K los 13917K
An unhandled exception occured.

**Comment by omares** [comment]
Could you please provide more information? Even better would be an sample app.

* Did your app crashed?
* Do you have any stack trace?
* What options do you use?

etc

**Comment by omares** [comment]
Closing because of missing information
