### ISSUE TITLE
Build prototype on Mac OS?

### ISSUE THREAD

**Issue by ronanrooney** [rebuy-de/rb-forms-barcode#46]
I'm on Mac OS (10.11.3), and I've got Xamarin Studio installed. I've poured over the NuGet website, and the only way to install it seems to be by using a Windows computer. Without NuGet, I do not believe there are instructions for installing rb-forms-barcode. Do you know if Mac users have been successful at using rb-forms-barcode in Xamarin? Thank you!

**Comment by omares** [comment]
hey ronanrooney, RbFormBarcode is purely build on a mac eco system so it should work without any issues :) Could you be more specific what your exact issue is? You know you can simply get the package by using nuget, so there is no need to build the package by yourself.

**Comment by omares** [comment]
Closing this because of missing feedback.
