### ISSUE TITLE
[Android] Can't build with API version 23

### ISSUE THREAD

**Issue by denchr** [rebuy-de/rb-forms-barcode#48]
Okay I'm quite new to Xamarin forms en general.
But can't seem to get the nuget packet to build on android with api version 23

I'm getting loads off definition errors in resource.designer.cs, see screenshot:
![screen](https://cloud.githubusercontent.com/assets/5169587/16655053/eb26758a-4458-11e6-87a1-52ca7e4207f7.jpg)

We are using XF 2.2.0.45, if that helps

Thanks in advance : )

**Comment by fvermeulen** [comment]
which barcode library version do you use? I updated the library already a few weeks ago with that fix. Otherwise I would try to clean everything, but I think it's an older version

**Comment by denchr** [comment]
You did? Sound awsome.
I'm using v.0.6.5

**Comment by fvermeulen** [comment]
mhh sorry i looked again and no i didn't build a version for that right now. 

There is a branch, where I updated the resources

https://github.com/rebuy-de/rb-forms-barcode/compare/update_google_play_services

Have to test it again, why I didn't add a pull request and build a new version with that solution

**Comment by denchr** [comment]
Did you find some time to look into this?

**Comment by fvermeulen** [comment]
Yes i made a pull request #55. I have to build a new version now and test everything. Update will go live today.

**Comment by fvermeulen** [comment]
Is done.
Update is live [nuget](https://www.nuget.org/packages/Rb.Forms.Barcode/0.7.1)
