### ISSUE TITLE
Xamarin cycle 8 compatibility issues

### ISSUE THREAD

**Issue by NaurisAndzans** [rebuy-de/rb-forms-barcode#56]
Yesterday I followed the release of the new and stable version of Xamarin and its components just to find that rb-forms-barcode is not longer working. So I dowloaded the sample project to see if the same problems occurs running clean sample and the problem does occur.

The problem persists every time.

As soon as I try to open the scanner page app crashes with the following message:
" **Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries.** "

Has anyone else experienced such behaviour after following the upgrade to cycle 8?

**Comment by fvermeulen** [comment]
Hello @NaurisAndzans 

I am as well on cycle 8 and everything is working on ios and android for me. Can you clean and build the project completly new please.

What are you doing. I need more infos to help you in this case.

**Comment by NaurisAndzans** [comment]
I forgot to add that I'm working on a Macbook and I encounter this problem only with iOS builds. Android builds works as expected.

As soon as the following line gets called the app crashes with the message I posted previously.  **Detail.Navigation.PushAndRemovePrevious(ScannerPageControl.Instance.CreateScannerPage(), 1);**

**Comment by fvermeulen** [comment]
we work as well on mac....

and you think that happens due to the scannerlibrary?

**Comment by armintelker** [comment]
can you please create a sample github project that contains the bug.

**Comment by NaurisAndzans** [comment]
>can you please create a sample github project that contains the bug.

No need, cause I used your original sample without introducing any new features for testing this behaviour. Any other information or additional logs I can provide you with ?

**Comment by armintelker** [comment]
@NaurisAndzans 
1. the exact build version
2. the version of the iphone
3. the version of ios
4. xcode version
5. if possible the complete stack trace.
6. mac os version

**Comment by NaurisAndzans** [comment]
@armintelker 
1. Rb.Forms.Barcode 0.6.6 and Rb.Forms.Barcode 0.7.1
2. 5S and iPad Air
3. iOS 10.0.1
4. XCode 8
5. Native stacktrace from our app. Your clean sample produced the same results as soon as I tried to access barcode library: 
![image 2016-09-19 at 12 54 55 pm](https://cloud.githubusercontent.com/assets/1781816/18714180/9a87c560-801d-11e6-84f4-e0ef60107ce7.png)
6. OSX 10.11.6

**Comment by jmockjm** [comment]
I am also experiencing the same issue.  Everything was working fine before iOS10.  Now, as soon as the page opens and gets past the default constructor, it crashes.  I am only testing with iOS and have not yet implemented for Android.

RB.Forms.Barcode 0.7.1
Xamarin Studio 6.1
Xamarin.iOS 10.0.0.6
XCode 8/iOS 10

**Comment by jmockjm** [comment]
I appears to be crashing in RootPage.xaml.cs line 21:  await cameraPermission.RequestCameraPermissionIfNeeded();

I am wondering if there is some new plist setting we need?

**Comment by jmockjm** [comment]
Yep, just figured out the solution.  

@NaurisAndzans add this to your info.plist:

Property: "Privacy - Camera Usage Description"
Value:  "Use the camera for XYZ"
