### ISSUE TITLE
How to prevent multiple barcode decoding results?

### ISSUE THREAD

**Issue by milanmilic** [rebuy-de/rb-forms-barcode#62]
I have a problem with prevention taking more than one scan results.
How to take only the first scanned result, and to ignore the rest. The problem occurs when on the screen displays several bar codes at the same time.

**Comment by rdoubleui** [comment]
Hi @milanmilic,

Not sure if I understand you right, the lib will raise an event any time there's a new bar code detected. So I'd think it's up to your logic to act upon an additional event notification. If I got you wrong, please elaborate and I'm pretty sure we can assist.

**Comment by rdoubleui** [comment]
In addition you can distinguish barcodes by barcode type, that could help to narrow down the amount being scanned, if you're are having [different types](https://github.com/rebuy-de/rb-forms-barcode/blob/master/Rb.Forms.Barcode.Pcl/Barcode.cs#L7) and don't aim to scan all those types.
